apiVersion: v1
kind: ConfigMap

metadata:
  name: student-config
  namespace: student

data:

  ASPNETCORE_ENVIRONMENT: "Development"

  DB_SERVER: "192.168.1.102"

  DB_PORT: "1433"

  DB_NAME: "StudentDB"
